using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Ninject.MockingKernel: Auto mocking kernel based on Ninject")]
[assembly: AssemblyCompanyAttribute("bbv Software Services AG")]
[assembly: AssemblyCopyrightAttribute("Copyright ? 2009-2011 bbv Software Services AG and contributors")]
[assembly: AssemblyVersionAttribute("3.2.0.0")]
[assembly: AssemblyFileVersionAttribute("3.2.2.1")]
[assembly: ComVisibleAttribute(false)]

