using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Ninject.MockingKernel: Auto mocking kernel based on Ninject")]
[assembly: AssemblyCompanyAttribute("bbv Software Services AG")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2009-2011 bbv Software Services AG and contributors")]
[assembly: AssemblyVersionAttribute("2.3.0.0")]
[assembly: AssemblyFileVersionAttribute("2.3.0.12")]
[assembly: ComVisibleAttribute(false)]

